#!/usr/bin/env bash

# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" && devbox_dir=$PWD

source "${devbox_dir}/scripts/functions.sh"

rabbitmq_url="$(minikube service magento2-rabbitmq --url)"
open ${rabbitmq_url}
