#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" && vagrant_dir=$PWD

source "${vagrant_dir}/scripts/functions.sh"
resetNestingLevel

if [[ ! $(isMinikubeRunning) -eq 1 ]]; then
    // TDOO: Eliminate duplication with k-restart
    minikube start --cache-images --cpus=2 --memory=4096 2> >(logError)
fi


info "$(regular)See details in $(bold)${vagrant_dir}/log/${current_script_name}.log$(regular). For debug output set $(bold)debug:vagrant_project$(regular) to $(bold)1$(regular) in $(bold)etc/config.yaml$(regular)"
