#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" && devbox_dir=$PWD

source "${devbox_dir}/scripts/functions.sh"

magento2_url_with_port80="http://$(getInstanceDomainName $(getContext))"
open ${magento2_url_with_port80}
