replicaCount: 1

image:
  repository: shiftedreality/magento-kubernetes-components-php
  tag: 7.1-fpm
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

#service:
#  type: NodePort
#  port: 8001
#  nodePort: 30301

xdebugService:
  type: NodePort
  port: 8002
  nodePort: 30302

monolith:
  name: magento2
  deployment:
    nginxImage: nginx:1.9
    codeImage: shiftedreality/magento-kubernetes-components-php
    imageTag: 7.1-fpm
    imagePullPolicy: Always
global:
  checkout:
    enabled: false
    db:
      enabled: false
    service:
      type: NodePort
      nodePort: 30102
      port: 80
  monolith:
    service:
      type: NodePort
      nodePort: 30301
      port: 8001
    mysqlHost: magento-mysql
    volumeHostPath: /Users/user/Projects/magento2-kubernetes-for-developers
  persistence:
    nfs:
      enabled: true # This value is overridden via <devbox_project>/etc/config.yaml
      serverIp: 192.168.99.1 # This value is overridden via <devbox_project>/etc/config.yaml

resources: {}
  # Uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  fullname: magento-mysql
  mysqlRootPassword: "123123q"
  service:
    type: NodePort
    nodePort: 30306
  persistence:
    size: 4Gi

redis:
  usePassword: false
  master:
    disableCommands: []
    persistence:
      enabled: false
  cluster:
    enabled: false

rabbitmq:
  serviceType: NodePort
  rabbitmq:
    username: admin
    password: 123123q

elasticsearch:
  imageTag: "6.7.1"
  esMajorVersion: 6

  replicas: 2
  minimumMasterNodes: 1

  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100M
