#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Changing Magento configuration to allow execution of functional tests"
incrementNestingLevel

"${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'cms/wysiwyg/enabled' 'disabled'
"${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'admin/security/admin_account_sharing' '1'
"${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'admin/security/use_form_key' '0'

decrementNestingLevel
