#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Configuring Varnish FPC according to config.yaml"
incrementNestingLevel

# Get args
while getopts 'f' flag; do
  case "${flag}" in
    f) force_restart_services=1 ;;
    *) error "Unexpected option" && decrementNestingLevel && exit 1;;
  esac
done

# Configure Varnish if enabled in config
restart_services=0
use_varnish="$(bash "${devbox_dir}/scripts/get_config_value.sh" "environment_use_varnish")"
if [[ $use_varnish == 1 ]]; then
    status "Updating Magento database to use varnish FPC"
    # TODO: Make credentials configurable
    mysql -u"root" -p"123123q" -h"magento2-mysql" -D magento -e "INSERT INTO core_config_data
        ( scope, scope_id, path, value ) VALUES
        ( 'default', '0', 'system/full_page_cache/caching_application', '2' )
         ON DUPLICATE KEY UPDATE value = 2
    ;"
else
    status "Updating Magento database to not use varnish FPC"
    mysql -u"root" -p"123123q" -h"magento2-mysql" -D magento -e "INSERT INTO core_config_data
        ( scope, scope_id, path, value ) VALUES
        ( 'default', '0', 'system/full_page_cache/caching_application', '1' )
         ON DUPLICATE KEY UPDATE value = 1
    ;"
fi

decrementNestingLevel
