#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Configuring Varnish FPC according to etc/env/config.yaml"
incrementNestingLevel

# Get args
while getopts 'f' flag; do
  case "${flag}" in
    f) force_restart_services=1 ;;
    *) error "Unexpected option" && decrementNestingLevel && exit 1;;
  esac
done

# Configure Varnish if enabled in config
restart_services=0
use_varnish="$(bash "${devbox_dir}/scripts/get_env_config_value.sh" "environment_use_varnish")"
if [[ $use_varnish == 1 ]]; then
    status "Updating Magento database to use varnish FPC"
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'system/full_page_cache/caching_application' '2'
else
    status "Updating Magento database to not use varnish FPC"
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'system/full_page_cache/caching_application' '1'
fi

decrementNestingLevel
