#!/usr/bin/env bash

# Init environment variables
devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Configuring search engine according to $(getContext).yaml"
incrementNestingLevel

if [[ -z "$(grep "search_engine:" ${devbox_dir}/etc/env/config.yaml)" ]]; then
    sed -i '/environment:/a \ \ search_engine: "mysql"' ${devbox_dir}/etc/env/config.yaml
fi

search_engine="$(bash "${devbox_dir}/scripts/get_env_config_value.sh" "environment_search_engine")"
if [[ ${search_engine} == "elasticsearch" ]]; then
    status "Configuring ElasticSearch search engine"
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/engine' 'elasticsearch6'
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/elasticsearch6_server_hostname' 'elasticsearch-master'
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/elasticsearch6_server_port' '9200'
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/elasticsearch6_index_prefix' 'magento2'
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/elasticsearch6_enable_auth' '0'
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/elasticsearch6_server_timeout' '15'
elif [[ ${search_engine} == "mysql" ]]; then
    status "Configuring MySQL search engine"
    "${DEVBOX_ROOT}/scripts/guest/update_magento_config" 'catalog/search/engine' 'mysql'
fi

bash "${DEVBOX_ROOT}/scripts/guest/m-clear-cache"

status "Rebuilding catalog search index"
php "${DEVBOX_ROOT}/$(getContext)/bin/magento" indexer:reindex catalogsearch_fulltext 2> >(logError) > >(log)

decrementNestingLevel
