#!/usr/bin/env bash

# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.

#function process_configs () {
#    configs_path=$1
#    configs=$2
#    for config in "${configs[@]}"
#    do
#        if [[ ! -d ${devbox_dir}/etc/guest/${config} ]] && [[ ! -f ${devbox_dir}/etc/guest/${config} ]]; then
#            if [[ -d ${configs_path}/${config} ]] || [[ -f ${configs_path}/${config} ]]; then
#                sudo rm -rf "${configs_path}/${config}.back"
#                sudo cp -rp ${configs_path}/${config} "${configs_path}/${config}.back"
#                sudo mv ${configs_path}/${config} ${devbox_dir}/etc/guest/${config}
#                sudo ln -s ${devbox_dir}/etc/guest/${config} ${configs_path}/${config}
#            fi
#        fi
#    done
#}
#
#devbox_dir="${devbox_dir}"
#
#source "${devbox_dir}/scripts/functions.sh"
#
## Below configuration is required to allow managing mysql as a service
#if ! cat /etc/apparmor.d/local/usr.sbin.mysqld | grep -q '${devbox_dir}/etc/guest' ; then
#    echo "
#        ${devbox_dir}/etc/guest/mysql/*.pem r,
#        ${devbox_dir}/etc/guest/mysql/conf.d/ r,
#        ${devbox_dir}/etc/guest/mysql/conf.d/* r,
#        ${devbox_dir}/etc/guest/mysql/*.cnf r," >> /etc/apparmor.d/local/usr.sbin.mysqld
#fi
#
#status "Making guest configs visible and editable in the host IDE"
#incrementNestingLevel
#
## Configs located under /etc/*
#config_dir="/etc"
## See unlink_configs script
#configs=( apache2 php mysql varnish rabbitmq )
#process_configs ${config_dir} ${configs}

decrementNestingLevel
