#!/usr/bin/env bash

# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

if [[ ${SKIP_CACHE_CLEAN} -eq 1 ]] ; then
    exit 0
fi

status "Clearing Magento cache"
incrementNestingLevel

status "Clearing directories containing temporary files"

mage_mode=$(bash "${devbox_dir}/scripts/get_config_value.sh" "magento_mode")

rm -f "${DEVBOX_ROOT}/$(getContext)/app/etc/paths.php"
if [[ -d "${DEVBOX_ROOT}/$(getContext)/var" ]]; then
    # clear var
    cd "${DEVBOX_ROOT}/$(getContext)"
    mv var/.htaccess var_htaccess.back
    if [[ -d "${DEVBOX_ROOT}/$(getContext)/var/generation" ]] && [[ ${mage_mode} == "production" ]]; then
        # for Magento v2.0.x and v2.1.x
        mv var/generation var_generation.back
    fi
    rm -rf var/* var/.[^.]*
    if [[ -f var_htaccess.back ]]; then
        mv var_htaccess.back var/.htaccess
    fi
    if [[ -d "${DEVBOX_ROOT}/$(getContext)/var_generation.back" ]] && [[ ${mage_mode} == "production" ]]; then
        mv var_generation.back var/generation
    fi
fi

if [[ -d "${DEVBOX_ROOT}/$(getContext)/generated" ]] && [[ ${mage_mode} != "production" ]]; then
    # for Magento v2.2.0 and greater
    cd "${DEVBOX_ROOT}/$(getContext)"
    rm -rf generated/*
fi

if [[ -d "${DEVBOX_ROOT}/$(getContext)/pub" ]] && [[ ${mage_mode} != "production" ]]; then
    # clear pub/statics
    cd "${DEVBOX_ROOT}/$(getContext)/pub" && mv static/.htaccess static_htaccess.back && rm -rf static && mkdir static
    if [[ -f static_htaccess.back ]]; then
        mv static_htaccess.back static/.htaccess
    fi
fi

if [[ -d "${DEVBOX_ROOT}/$(getContext)/dev" ]]; then
    # clear integration tests tmp
    cd "${DEVBOX_ROOT}/$(getContext)/dev/tests/integration" && mv tmp/.gitignore tmp_gitignore.back && rm -rf tmp && mkdir tmp
    if [[ -f tmp_gitignore.back ]]; then
        mv tmp_gitignore.back tmp/.gitignore
    fi
    # clear unit tests tmp
    cd "${DEVBOX_ROOT}/$(getContext)/dev/tests/unit" && mv tmp/.gitignore tmp_gitignore.back && rm -rf tmp && mkdir tmp
    if [[ -f tmp_gitignore.back ]]; then
        mv tmp_gitignore.back tmp/.gitignore
    fi
fi

status "Flushing redis storage"
redis-cli -h magento2-redis-master flushall 2> >(logError) > >(log)

if [[ -f "${DEVBOX_ROOT}/$(getContext)/app/etc/env.php" ]]; then

    bash "${DEVBOX_ROOT}/scripts/guest/configure_debugging"

    status "Flushing cache using 'bin/magento cache:flush'"
    php "${DEVBOX_ROOT}/$(getContext)/bin/magento" cache:flush 2> >(logError) > >(log)
fi

decrementNestingLevel
