#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Configuring search engine"
incrementNestingLevel

if [[ $1 == "help" ]]; then
    status "Usage: ./m-search-engine mysql/elasticsearch"
    decrementNestingLevel
    exit 0
fi


# Check if user created $(getContext).yaml file
if [[ ! -f ${devbox_dir}/etc/env/config.yaml ]]; then
    error "Please make sure you have create a $(getContext).yaml file copy from etc/instance/config.yaml.dist"
    decrementNestingLevel
    exit 1
fi

if [[ -z "$(grep "search_engine:" ${devbox_dir}/etc/env/config.yaml)" ]]; then
    sed -i '/environment:/a \ \ search_engine: "mysql"' ${devbox_dir}/etc/env/config.yaml
fi

if [[ $1 == "mysql" ]]; then
    status "Enabling MySQL search engine"
    sed -ie 's/search_engine:.*/search_engine: "mysql"/' ${devbox_dir}/etc/env/config.yaml
elif [[ $1 == "elasticsearch" ]]; then
    status "Enabling ElasticSearch search engine"
    sed -ie 's/search_engine:.*/search_engine: "elasticsearch"/' ${devbox_dir}/etc/env/config.yaml
else
    error "Usage: ./m-search-engine mysql|elasticsearch"
    decrementNestingLevel
    exit 1
fi

bash "${DEVBOX_ROOT}/scripts/guest/configure_search_engine"

decrementNestingLevel
