#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

status "Configuring Varnish"
incrementNestingLevel

if [[ $1 == "help" ]]; then
    status "Usage: ./m-varnish enable/disable"
    decrementNestingLevel
    exit 0
fi

if [[ ! -f ${devbox_dir}/etc/env/config.yaml ]]; then
    error "Please make sure you have copied etc/env/config.yaml from etc/env/config.yaml.dist"
    decrementNestingLevel
    exit 1
fi

if [[ $1 == "enable" ]]; then
    status "Enabling Varnish"
    sed -ie "s/use_varnish:.*/use_varnish: 1/" ${devbox_dir}/etc/env/config.yaml
elif [[ $1 == "disable" ]]; then
    status "Disabling Varnish"
    sed -ie "s/use_varnish:.*/use_varnish: 0/" ${devbox_dir}/etc/env/config.yaml
else
    error "Usage: ./m-varnish enable|disable"
    decrementNestingLevel
    exit 1
fi

bash "${devbox_dir}/scripts/guest/configure_varnish"

decrementNestingLevel
